name: Docker CI - GifsApp
on:
  push:
    branches: [ "GifsApp" ]
  pull_request:
    branches: [ "GifsApp" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      id: semver
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${increment}"


    - name: Export version
      run: echo "NEW_VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV


    - name: Show calculated version
      run: echo "Version = $NEW_VERSION"


    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin


    - name: Build & Push Multi-Arch Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          VITE_GIPHY_API_KEY=${{ secrets.VITE_GIPHY_API_KEY }}
        tags: |
          anderortiz/gifs-app:${{ env.NEW_VERSION }}
          anderortiz/gifs-app:latest